apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: simplechat-dev
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: simplechat-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: simple-chat-api
  namespace: simplechat-dev
  labels:
    app: simple-chat-api
spec:
  ports:
  - port: 80
    targetPort: 82
  selector:
    app: simple-chat-api
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-chat-api
  namespace: simplechat-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-chat-api
    spec:
      containers:
      - name: simple-chat-api
        image: jcorioland/simple-chat-api:latest
        ports:
        - containerPort: 82
        env:
        - name: SIMPLE_CHAT_REDIS_ENDPOINT
          value: redis:6379
---